services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - default
      - dev-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-gateway.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-gateway.loadbalancer.server.port=80"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker/development/nginx
    volumes:
      - ./frontend:/app

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      MAILER_FROM_EMAIL: info@auction.test
      MAILER_HOST: mailpit
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      FRONTEND_URL: http://auction.test:8080
    volumes:
      - ./api:/app
  
  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      MAILER_FROM_EMAIL: info@auction.test
      MAILER_HOST: mailpit
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      FRONTEND_URL: http://auction.test:8080
    volumes:
      - ./api:/app
    networks:
      - dev-proxy
  
  api-postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

networks:
  default:
  dev-proxy:
    external: true

volumes:
  api-postgres: