---
- name: Install Docker SDK dependencies
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
      - python3-venv
    state: present
    update_cache: yes

- name: Create a virtual environment for Docker SDK
  command: python3 -m venv /opt/docker-venv
  args:
    creates: /opt/docker-venv

- name: Install Docker SDK in virtual environment
  pip:
    name: docker
    virtualenv: /opt/docker-venv
