name: Pipeline

on:
  push:
    branches:
      - github-actions
  
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io/deepydee/slim-auction
  REGISTRY_HOST: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v2

      - name: Cache API composer
        uses: actions/cache@v4
        with:
          path: api/vendor
          key: api-composer-${{ hashFiles('api/composer.lock') }}

      - name: Cache frontend yarn
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: frontend-yarn-${{ hashFiles('frontend/yarn.lock') }}

      - name: Cache cucumber yarn
        uses: actions/cache@v4
        with:
          path: cucumber/node_modules
          key: cucumber-yarn-${{ hashFiles('cucumber/yarn.lock') }}

      - name: Docker login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY_HOST }}
          username: ElisDN
          password: ${{ github.token }}

      - name: Dev Init
        run: make init

      - name: Push dev cache images
        run: make push-dev-cache

      - name: Validate
        run: make api-validate-schema

      - name: Lint API
        run: make api-lint

      - name: Lint Frontend
        run: make frontend-lint

      - name: Analyze API
        run: make api-analyze

      - name: Test API
        id: api-test
        run: make api-test

      - name: Archive tests output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: api/var/log
        if: ${{ always() && steps.api-test.outcome == 'failure' }}

      - name: Test Frontend
        run: make frontend-test

      - name: Dev Down
        run: make docker-down-clear

      - name: Build
        run: make build
