name: Pipeline

on:
  push:
    branches:
      - github-actions
  
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io/deepydee/slim-auction
  REGISTRY_HOST: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Cache API composer
        uses: actions/cache@v4
        with:
          path: api/vendor
          key: api-composer-${{ hashFiles('api/composer.lock') }}

      - name: Cache frontend yarn
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: frontend-yarn-${{ hashFiles('frontend/yarn.lock') }}

      - name: Cache cucumber yarn
        uses: actions/cache@v4
        with:
          path: cucumber/node_modules
          key: cucumber-yarn-${{ hashFiles('cucumber/yarn.lock') }}

      - name: Docker login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY_HOST }}
          username: ElisDN
          password: ${{ github.token }}

      - name: Dev Init
        run: make init
