name: Pipeline

on:
  push:
    branches:
      - github-actions
  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
